### ISSUE TITLE
Documentation and collaboration processes

### ISSUE THREAD

**Issue by ratstache** [asikkenga/devClub#4]
This will seem excessive but I'm overdoing it because I need to start thinking about all of our projects going forward

## Problem
The larger goal of creating a standardized workflow close to that in industry hasn't been achieved yet. However, we have a project open for collaboration without any predetermined process laid out. Relying on collaborators prior knowledge is tricky because every workplace is different and collaborators are coming into this from many different backgrounds.

## Solution
To avoid confusion, miscommunication, and other potential issues we need to prioritize a process specific to this project to allow development to continue without being blocked waiting for the larger effort.

We need to discuss:
- [x] a standard **workflow**
- [x] clear expectations and process for **merge requests**
- [ ] how to conduct **code reviews** properly and efficiently
- [ ] what **coding standards** we expect
- [ ] how to **log issues** on the project
- [ ] how to **organize issues** for the project

After agreement, create new issues for each piece of documentation and assign it (likely all to ratstache because everyone hates documentation)

### workflow
should we have everyone fork the repo, work off their own copy, then create merge requests back into this repo **OR** just create a standard way to name branches.

ex. (name)_(issue) ```landon_mobileSpacingFix```

### merge requests 
Merge requests should link back to their respective issues, it was mentioned that screenshots should be included I agree with that as long as the change is visual. A short description of the problem, a short description of what the solution is, and some reasoning for your decisions even if they were straightforward should all be included.

### code reviews
I think the most important thing with these code reviews will be the attitude of the reviewer, we need to provide encouraging feedback. Comments and discussion should be encouraged.

### coding standards
I don't know enough about the project to step in here, I'm going to need some help form @asikkenga and @playnich8. The good thing is we can kind of take this as we go and refactor things as we come to a concensus. What languages are being used? What style is expected? any caveats or oddities with any of the tools we're using? Fill me in.

### logging issues
Issues don't need to be this long or detailed this is just how I do it. Someone needs to be able to read the description and  clearly understand what the issue is. Beyond that I think it's up to the writers best judgement, but I would like to hear what your opinions on this are.

### organizing issues
We need to be able to organize issues based on priority, probably skill level required, and probably required skills. That way someone with css experience can easily pick up an issue that only requires css or someone wanting to learn html can assign themselves and

**Comment by jennifertran** [comment]
I have a suggestion in terms of the workflow process, we can use or build on what we originally did with the previous devClub repo [here](https://github.com/umdevclub/umdevclub.github.io). So far there's only a bunch of labeled issues, a kanban board, a wiki page, and barely any code done in the repo. I was thinking maybe we could try merging the workflow with what we currently have right now?

Let me know your thoughts.

**Comment by ratstache** [comment]
This issue has been moved to the umdevclub organization repo [link here](https://github.com/umdevclub/devClub/issues/3). Closing this.
