### ISSUE TITLE
Mobile hamburger menu doesn't close when an item is selected

### ISSUE THREAD

**Issue by ratstache** [asikkenga/devClub#5]
## Problem
When selecting an item from the hamburger menu on mobile the selection works but the menu remains open which takes up quite a bit of the screen. The menu also remains open if you click away from it (if you click the bottom half of the screen)

![image](https://user-images.githubusercontent.com/8846353/27568922-4590309c-5aba-11e7-8155-8a45fc635477.png)

## Fix
We want this to automatically close both when an item in the menu is selected and when you click away from the menu.

**Comment by asikkenga** [comment]
Updated the js. Mobile menu is fixed to close when link is clicked or if there is a click outside the menu
